sudo: required

notifications:
  email: false

services:
  - docker

language: go

script:
  - make

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker push cwmr/cha.dweimer.com:amd64
      docker push cwmr/cha.dweimer.com:armhf
      docker run --rm mplatform/manifest-tool --username $DOCKER_USER --password $DOCKER_PASS push from-spec manifest.yml
    else
      docker tag cwmr/cha.dweimer.com:amd64 cwmr/cha.dweimer.com:amd64-dev
      docker tag cwmr/cha.dweimer.com:armhf cwmr/cha.dweimer.com:armhf-dev
      docker push cwmr/cha.dweimer.com:amd64-dev
      docker push cwmr/cha.dweimer.com:armhf-dev
      docker run --rm mplatform/manifest-tool --username $DOCKER_USER --password $DOCKER_PASS push from-spec manifest.dev.yml
    fi
