baseurl = "https://cha.dweimer.com/"
title = "while my code's compiling"
languageCode = "en-us"
theme = "beautifulhugo"
publishdir = "docs"
googleAnalytics = "UA-19191579-6"

[Author]
    name = "Chad Weimer"
    github = "https://github.com/chadweimer"

[Taxonomies]
    tag = "tags"

[Params]
    logo = "img/avatar.png"
    subtitle = "Personal blog of Chad Weimer, where I sometimes post (possibly) insightful things."

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2
