baseurl = "https://cha.dweimer.com/"
title = "while my code's compiling"
languageCode = "en-us"
theme = "beautifulhugo"
googleAnalytics = "UA-19191579-6"

[author]
    name = "Chad Weimer"
    github = "chadweimer"

[params]
    logo = "img/avatar-icon.png"
    subtitle = "Personal blog of Chad Weimer, where I sometimes post (possibly) insightful things."

[permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/page/about/me/"
    weight = 2
